### ISSUE TITLE
Audio Error - Fedora

### ISSUE THREAD

**Issue by Zel9278** [EXALAB/AnLinux-App#7] opened 2018-10-21 08:54 UTC
Can you still use the sound?

**Comment by exalab999** [comment] 2018-10-22 12:47
It is not possible to output sound currently, this is a technical limitation.

**Comment by supersonictw** [comment] 2018-10-23 09:48
It is very difficult that play music on AnLinux even LinuxOnAndroid have never been done.
Because it relatives the firmwares of your device, we could not make images which for every devices around the world. :(

Maybe you can hack it by yourself
Good Luck ;)

**Comment by Zel9278** [comment] 2018-10-23 10:03
> It is very difficult that play music on AnLinux even LinuxOnAndroid have never been done.
> Because it relatives the firmwares of your device, we could not make images which for every devices around the world. :(
> 
> Maybe you can hack it by yourself
> Good Luck ;)

Ok
email address: countbaster@gmail.com

**Comment by twaik** [comment] 2018-11-12 14:52
Termux has pulseaudio with android output, you can use it. Also maintainers can prebuild pulseaudio to be used inside the app, it can be built with Android NDK. See https://github.com/twaik/pulseaudio-sles-ndk. My Pulseaudio Android backend works and is used in Termux. You will need to add `export PULSE_SERVER=localhost:4712` line to xinitrc or DE startup script to use it.

**Comment by exalab999** [comment] 2018-11-13 05:37
@twaik Thanks a lot for the info! We will look into this.

**Comment by B3N4K** [comment] 2019-05-28 08:00
Can confirm, everything that is needed for audio playback **is already available**. You need to install pulseaudio in termux, make it available for localhost clients (see [archlinux wiki](https://wiki.archlinux.org/index.php/PulseAudio#On_the_server) for simple tutorial) and then use the pulseaudio server as your sound device in the guest OS.

Beware of one thing - pulseaudio quits after 20 seconds of not receiving any inputs by default, so you might want to put `exit-idle-time = -1` in your `daemon.conf` (this will stop pulseaudio from quitting for being idle - good for testing, but for production you might want put there some real value lika 3600 or smth).

Source: I am successfully running [Mopidy](https://www.mopidy.com/) with [party plugin](https://github.com/Lesterpig/mopidy-party) to make my phone portable jukebox playing anything available from YouTube or Spotify. Works great, there is only little delay on playing first song, but that is not audio-related.

I'd suggest closing this issue or at least relabeling it (as it's not a bug).

**Comment by imprakharshukla** [comment] 2019-09-10 02:53
If you guys are looking to extent your linux setup with Audio, you can give **Andronix**  a try. We support audio output with Ubuntu KDE and all other distros. 

https://andronix.tech

**Comment by anesuc** [comment] 2022-01-29 01:57
No one here really gave step by step instructions that ae easy to follow that just work.

Run the following command in Termux (Not inside Linux, make sure you are not inside ./start-ubuntu or the equivalent script, but just in the root of Termux ):

 pkg install wget && wget https://andronixos.sfo2.cdn.digitaloceanspaces.com/OS-Files/setup-audio.sh && chmod +x setup-audio.sh && ./setup-audio.sh
 
 You can now start ubuntu or whatever distro and your sound should now be working. I am not sure if I had installed anything before this, so let me know if it doesn't work.
 
 I am using the full KDE installation incase that has more of the pulseaudio setup than the normal one.
 
 Source from another Linux on Android project called Andronix: https://docs.andronix.app/troubleshoot/sound/

**Comment by exalab999** [comment] 2022-11-14 02:39
Audio is now available.

**Closed by exalab999** 2022-11-14 02:39 UTC
Labels: question
