### ISSUE TITLE
ssh username and password

### ISSUE THREAD

**Issue by wbhuangxm** [EXALAB/AnLinux-App#44] opened 2018-12-28 16:57 UTC
When install desktop environment,   you are asked to  provide a vnc username and password 
However , when install ssh , no such action are required.
OpenBSD Secure Shell Server  seems to be installed successfully and can be launched. 
When I use an android ssh client, Termius, to connect to the server, A username is required. What is the username ? I have tried " root", but failed.

**Comment by exalab999** [comment] 2018-12-30 13:06
Closed as duplicate of #41

**Closed by exalab999** 2018-12-30 13:06 UTC
