### ISSUE TITLE
Unable to locate package (xfce4, xfce4-terminal, tightvncserver) - ubuntu - setegid (38: Function not implemented)

### ISSUE THREAD

**Issue by smilearric** [EXALAB/AnLinux-App#37] opened 2018-12-15 13:48 UTC
Hello,

I've already had a look at the opened and closed issues. None seem to help.

I previously encountered https: #3#issuecomment-447565823

**My specs:** 

• OnePlus 5T (ONEPLUS A5010)
• Android 9 (kernel 4.4.153-perf+ `#1`)
• OxygenOS OP5T_O2_BETA_20
• Build ONEPLUS A5010_43_181205
• disabled GAPPS & Google Play Services

**Apps from f-droid:** 

• Termux v.0.65
• AnLinux v.4.94

**Apps from Yalp store:** 

- VNC Viewer

**Blokada adblocker disabled.** 

**Problem:**  I cannot get xfce and the VNC server:

```
Welcome to Termux!

$ pkg install wget proot -y && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Ubuntu/ubuntu.sh && bash ubuntu.sh
Get:1 https://termux.net stable InRelease [1720 B]
Get:2 https://termux.net stable/main all Packages [5496 B]
Get:3 https://termux.net stable/main aarch64 Packages [65.9 kB]
Fetched 73.1 kB in 1s (70.7 kB/s)
Reading package lists... Done
Building dependency tree... Done
8 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  libtalloc libunistring libuuid pcre2
The following NEW packages will be installed:
  libtalloc libunistring libuuid pcre2 proot wget
0 upgraded, 6 newly installed, 0 to remove and 8 not upgraded.
Need to get 867 kB of archives.
After this operation, 3748 kB of additional disk space will be used.
Get:1 https://termux.net stable/main aarch64 libtalloc aarch64 2.1.14 [9660 B]
Get:2 https://termux.net stable/main aarch64 libunistring aarch64 0.9.10 [366 kB]
Get:3 https://termux.net stable/main aarch64 libuuid aarch64 1.0.3-2 [4416 B]
Get:4 https://termux.net stable/main aarch64 pcre2 aarch64 10.32 [235 kB]
Get:5 https://termux.net stable/main aarch64 proot aarch64 5.1.107-18 [60.0 kB]
Get:6 https://termux.net stable/main aarch64 wget aarch64 1.20 [192 kB]
Fetched 867 kB in 0s (1984 kB/s)
Selecting previously unselected package libtalloc.
(Reading database ... 416 files and directories currently installed.)
Preparing to unpack .../0-libtalloc_2.1.14_aarch64.deb ...
Unpacking libtalloc (2.1.14) ...
Selecting previously unselected package libunistring.
Preparing to unpack .../1-libunistring_0.9.10_aarch64.deb ...
Unpacking libunistring (0.9.10) ...
Selecting previously unselected package libuuid.
Preparing to unpack .../2-libuuid_1.0.3-2_aarch64.deb ...
Unpacking libuuid (1.0.3-2) ...
Selecting previously unselected package pcre2.
Preparing to unpack .../3-pcre2_10.32_aarch64.deb ...
Unpacking pcre2 (10.32) ...
Selecting previously unselected package proot.
Preparing to unpack .../4-proot_5.1.107-18_aarch64.deb ...
Unpacking proot (5.1.107-18) ...
Selecting previously unselected package wget.
Preparing to unpack .../5-wget_1.20_aarch64.deb ...
Unpacking wget (1.20) ...
Setting up libtalloc (2.1.14) ...
Setting up libunistring (0.9.10) ...
Setting up pcre2 (10.32) ...
Setting up libuuid (1.0.3-2) ...
Setting up proot (5.1.107-18) ...
Setting up wget (1.20) ...
--2018-12-15 13:10:47--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Ubuntu/ubuntu.sh
Resolving raw.githubusercontent.com... 151.101.36.133
Connecting to raw.githubusercontent.com|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2091 (2.0K) [text/plain]
Saving to: ‘ubuntu.sh’

ubuntu.sh     100%   2.04K  --.-KB/s    in 0.001s

2018-12-15 13:10:48 (3.81 MB/s) - ‘ubuntu.sh’ saved [2091/2091]

Download Rootfs, this may take a while base on your internet speed.
--2018-12-15 13:10:48--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Rootfs/Ubuntu/arm64/ubuntu-rootfs-arm64.tar.gz
Resolving raw.githubusercontent.com... 151.101.36.133
Connecting to raw.githubusercontent.com|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 62995584 (60M) [application/octet-stream]
Saving to: ‘ubuntu-rootfs.tar.gz’

ubuntu-rootfs 100%  60.08M  7.69MB/s    in 10s

2018-12-15 13:10:59 (5.84 MB/s) - ‘ubuntu-rootfs.tar.gz’ saved [62995584/62995584]
root@localhost:~# wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/de-apt-xfce4.sh && bash de-apt-xfce4.sh
--2018-12-15 12:48:20--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/de-apt-xfce4.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...                                                  Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1299 (1.3K) [text/plain]
Saving to: ‘de-apt-xfce4.sh’

de-apt-xfce4. 100%   1.27K  --.-KB/s    in 0s

2018-12-15 12:48:20 (25.3 MB/s) - ‘de-apt-xfce4.sh’ saved [1299/1299]

E: setegid 65534 failed - setegid (38: Function not implemented)
E: setegid 0 failed - setegid (38: Function not implemented)
Reading package lists... Done
E: setegid 65534 failed - setegid (38: Function not implemented)
E: setegid 0 failed - setegid (38: Function not implemented)
E: Method gave invalid 400 URI Failure message: Failed to set new group ids - setresgid (38: Function not implemented)
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package xfce4
E: Unable to locate package xfce4-terminal
E: Unable to locate package tightvncserver
--2018-12-15 12:48:22--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/xstartup
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 110 [text/plain]
Saving to: ‘/root/.vnc/xstartup’

xstartup      100%     110  --.-KB/s    in 0s

2018-12-15 12:48:22 (1.31 MB/s) - ‘/root/.vnc/xstartup’ saved [110/110]

--2018-12-15 12:48:22--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/vncserver-start
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 98 [text/plain]
Saving to: ‘/usr/local/bin/vncserver-start’

vncserver-sta 100%      98  --.-KB/s    in 0s

2018-12-15 12:48:23 (2.22 MB/s) - ‘/usr/local/bin/vncserver-start’ saved [98/98]

--2018-12-15 12:48:23--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/vncserver-stop
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 54 [text/plain]
Saving to: ‘/usr/local/bin/vncserver-stop’

vncserver-sto 100%      54  --.-KB/s    in 0s

2018-12-15 12:48:23 (643 KB/s) - ‘/usr/local/bin/vncserver-stop’ saved [54/54]


You can now start vncserver by running vncserver-start

It will ask you to enter a password when first time starting it.

The VNC Server will be started at 127.0.0.1:5901

You can connect to this address with a VNC Viewer you prefer

Connect to this address will open a window with Xfce4 Desktop Environment



Running vncserver-start



To Kill VNC Server just run vncserver-stop



/usr/local/bin/vncserver-start: line 4: vncserver: command not found

root@localhost:~#
```

Regards
AR

**Comment by exalab999** [comment] 2018-12-15 14:15
Thanks for reporting this bug, it is a duplicate of [#36](https://github.com/EXALAB/AnLinux-App/issues/36).

Don't worry, we would look into this and see if it could be fixed.

**Closed by exalab999** 2018-12-15 14:15 UTC
Labels: duplicate

**Comment by TSMaitry** [comment] 2020-02-05 10:45
```
$ wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scr
ipts/DesktopEnvironment/Apt/Xfce4/de-apt-xfce4.sh && bash de-apt-xfce4.sh
--2020-02-05 16:13:03--  https://raw.githubusercontent.com/EXALAB/AnLinux-Re
sources/master/Scripts/DesktopEnvironment/Apt/Xfce4/de-apt-xfce4.sh
Resolving raw.githubusercontent.com... 151.101.152.133
Connecting to raw.githubusercontent.com|151.101.152.133|:443... connected.
HTTP request sent, awaiting response... 200 OK                Length: 1336 (
1.3K) [text/plain]
Saving to: ‘de-apt-xfce4.sh.1’

de-apt-xfce4.sh 100%[=====>]   1.30K  --.-KB/s    in 0s

2020-02-05 16:13:04 (12.6 MB/s) - ‘de-apt-xfce4.sh.1’ saved [1336/1336]

Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/termux-root-packages-24 root InRelease 
                                                Ign:4 https://dl.bintray.com
/grimler/science-packages-24 science InRelease
Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Get:6 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:6 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:8 https://dl.bintray.com/grimler/termux-root-packages-24 root Release [6
185 B]
Hit:8 https://dl.bintray.com/grimler/termux-root-packages-24 root Release
Get:10 https://dl.bintray.com/grimler/science-packages-24 science Release [5
348 B]
Hit:10 https://dl.bintray.com/grimler/science-packages-24 science Release
Get:5 https://dl.bintray.com/termux/termux-packages-24 stable Release [6061 
B]
Hit:5 https://dl.bintray.com/termux/termux-packages-24 stable Release
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package xfce4
E: Unable to locate package xfce4-terminal
E: Unable to locate package tightvncserver
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package xfe
mkdir: cannot create directory ‘/data/data/com.termux/files/home/.vnc’: File
 exists
--2020-02-05 16:13:13--  https://raw.githubusercontent.com/EXALAB/AnLinux-Re
sources/master/Scripts/DesktopEnvironment/Apt/Xfce4/xstartup
Resolving raw.githubusercontent.com... 151.101.152.133
Connecting to raw.githubusercontent.com|151.101.152.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 47 [text/plain]
Saving to: ‘/data/data/com.termux/files/home/.vnc/xstartup.6’

xstartup.6         100%[================>]      47  --.-KB/s    in 0s

2020-02-05 16:13:13 (501 KB/s) - ‘/data/data/com.termux/files/home/.vnc/xsta
rtup.6’ saved [47/47]

--2020-02-05 16:13:13--  https://raw.githubusercontent.com/EXALAB/AnLinux-Re
sources/master/Scripts/DesktopEnvironment/Apt/Xfce4/vncserver-start
Resolving raw.githubusercontent.com... 151.101.152.133
Connecting to raw.githubusercontent.com|151.101.152.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 98 [text/plain]
/usr/local/bin: No such file or directory
/usr/local/bin/vncserver-start: No such file or directory

Cannot write to ‘/usr/local/bin/vncserver-start’ (Success).
--2020-02-05 16:13:13--  https://raw.githubusercontent.com/EXALAB/AnLinux-Re
sources/master/Scripts/DesktopEnvironment/Apt/Xfce4/vncserver-stop
Resolving raw.githubusercontent.com... 151.101.152.133
Connecting to raw.githubusercontent.com|151.101.152.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 100 [text/plain]
/usr/local/bin: No such file or directory
/usr/local/bin/vncserver-stop: No such file or directory

Cannot write to ‘/usr/local/bin/vncserver-stop’ (Success).
chmod: cannot access '/usr/local/bin/vncserver-start': No such file or direc
tory
chmod: cannot access '/usr/local/bin/vncserver-stop': No such file or direct
ory

You can now start vncserver by running vncserver-start

It will ask you to enter a password when first time starting it.

The VNC Server will be started at 127.0.0.1:5901

You can connect to this address with a VNC Viewer you prefer

Connect to this address will open a window with Xfce4 Desktop Environment



Running vncserver-start



To Kill VNC Server just run vncserver-stop



de-apt-xfce4.sh: line 41: /etc/profile: Read-only file system
de-apt-xfce4.sh: line 42: /etc/profile: No such file or directory
de-apt-xfce4.sh: line 44: vncserver-start: command not found
$
```

**Comment by TSMaitry** [comment] 2020-02-05 10:46
**What is wrong with my Termux?**
Pls fix it😌😌😌

**Comment by TSMaitry** [comment] 2020-02-05 11:02
It happened when vnc desktop environment is running and you will have been clear the cache of Termux. Because I was deos it. After I'm was trying to install another linux distribution from Anlinux app and obtained this kind of problems. I think no one can fix it because I does hard reset of my smartphone, for to fix this errors after refractor but nothing happened?

**Comment by SinghLearnings** [comment] 2021-01-04 07:03
Hello....

When I am trying to Kali Linux on Android using termux...
After completing all the process VNCSERVER shows grey screen.
I use this all commands for installing Linux on Android.
Please check whats wrong with it...
1>
apt update && apt upgrade

2>
pkg install wget openssl-tool proot -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Kali/kali.sh && bash kali.sh

3>
./start-kali.sh

4> 
wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/de-apt-xfce4.sh && bash de-apt-xfce4.sh


Please fix this Problem

**Comment by adbo583** [comment] 2021-02-11 16:48
$ pkg install wget proot -y && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Ubuntu/ubuntu.sh && bash ubuntu.sh
Get:1 https://termux.net stable InRelease [1720 B]
Get:2 https://termux.net stable/main all Packages [5496 B]
Get:3 https://termux.net stable/main aarch64 Packages [65.9 kB]
Fetched 73.1 kB in 1s (70.7 kB/s)
Reading package lists... Done
Building dependency tree... Done
8 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  libtalloc libunistring libuuid pcre2
The following NEW packages will be installed:
  libtalloc libunistring libuuid pcre2 proot wget
0 upgraded, 6 newly installed, 0 to remove and 8 not upgraded.
Need to get 867 kB of archives.
After this operation, 3748 kB of additional disk space will be used.
Get:1 https://termux.net stable/main aarch64 libtalloc aarch64 2.1.14 [9660 B]
Get:2 https://termux.net stable/main aarch64 libunistring aarch64 0.9.10 [366 kB]
Get:3 https://termux.net stable/main aarch64 libuuid aarch64 1.0.3-2 [4416 B]
Get:4 https://termux.net stable/main aarch64 pcre2 aarch64 10.32 [235 kB]
Get:5 https://termux.net stable/main aarch64 proot aarch64 5.1.107-18 [60.0 kB]
Get:6 https://termux.net stable/main aarch64 wget aarch64 1.20 [192 kB]
Fetched 867 kB in 0s (1984 kB/s)
Selecting previously unselected package libtalloc.
(Reading database ... 416 files and directories currently installed.)
Preparing to unpack .../0-libtalloc_2.1.14_aarch64.deb ...
Unpacking libtalloc (2.1.14) ...
Selecting previously unselected package libunistring.
Preparing to unpack .../1-libunistring_0.9.10_aarch64.deb ...
Unpacking libunistring (0.9.10) ...
Selecting previously unselected package libuuid.
Preparing to unpack .../2-libuuid_1.0.3-2_aarch64.deb ...
Unpacking libuuid (1.0.3-2) ...
Selecting previously unselected package pcre2.
Preparing to unpack .../3-pcre2_10.32_aarch64.deb ...
Unpacking pcre2 (10.32) ...
Selecting previously unselected package proot.
Preparing to unpack .../4-proot_5.1.107-18_aarch64.deb ...
Unpacking proot (5.1.107-18) ...
Selecting previously unselected package wget.
Preparing to unpack .../5-wget_1.20_aarch64.deb ...
Unpacking wget (1.20) ...
Setting up libtalloc (2.1.14) ...
Setting up libunistring (0.9.10) ...
Setting up pcre2 (10.32) ...
Setting up libuuid (1.0.3-2) ...
Setting up proot (5.1.107-18) ...
Setting up wget (1.20) ...
--2018-12-15 13:10:47--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Ubuntu/ubuntu.sh
Resolving raw.githubusercontent.com... 151.101.36.133
Connecting to raw.githubusercontent.com|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2091 (2.0K) [text/plain]
Saving to: ‘ubuntu.sh’

ubuntu.sh     100%   2.04K  --.-KB/s    in 0.001s

2018-12-15 13:10:48 (3.81 MB/s) - ‘ubuntu.sh’ saved [2091/2091]

Download Rootfs, this may take a while base on your internet speed.
--2018-12-15 13:10:48--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Rootfs/Ubuntu/arm64/ubuntu-rootfs-arm64.tar.gz
Resolving raw.githubusercontent.com... 151.101.36.133
Connecting to raw.githubusercontent.com|151.101.36.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 62995584 (60M) [application/octet-stream]
Saving to: ‘ubuntu-rootfs.tar.gz’

ubuntu-rootfs 100%  60.08M  7.69MB/s    in 10s

2018-12-15 13:10:59 (5.84 MB/s) - ‘ubuntu-rootfs.tar.gz’ saved [62995584/62995584]
root@localhost:~# wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/de-apt-xfce4.sh && bash de-apt-xfce4.sh
--2018-12-15 12:48:20--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/de-apt-xfce4.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...                                                  Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1299 (1.3K) [text/plain]
Saving to: ‘de-apt-xfce4.sh’

de-apt-xfce4. 100%   1.27K  --.-KB/s    in 0s

2018-12-15 12:48:20 (25.3 MB/s) - ‘de-apt-xfce4.sh’ saved [1299/1299]

E: setegid 65534 failed - setegid (38: Function not implemented)
E: setegid 0 failed - setegid (38: Function not implemented)
Reading package lists... Done
E: setegid 65534 failed - setegid (38: Function not implemented)
E: setegid 0 failed - setegid (38: Function not implemented)
E: Method gave invalid 400 URI Failure message: Failed to set new group ids - setresgid (38: Function not implemented)
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package xfce4
E: Unable to locate package xfce4-terminal
E: Unable to locate package tightvncserver
--2018-12-15 12:48:22--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/xstartup
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 110 [text/plain]
Saving to: ‘/root/.vnc/xstartup’

xstartup      100%     110  --.-KB/s    in 0s

2018-12-15 12:48:22 (1.31 MB/s) - ‘/root/.vnc/xstartup’ saved [110/110]

--2018-12-15 12:48:22--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/vncserver-start
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 98 [text/plain]
Saving to: ‘/usr/local/bin/vncserver-start’

vncserver-sta 100%      98  --.-KB/s    in 0s

2018-12-15 12:48:23 (2.22 MB/s) - ‘/usr/local/bin/vncserver-start’ saved [98/98]

--2018-12-15 12:48:23--  https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/DesktopEnvironment/Apt/Xfce4/vncserver-stop
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 54 [text/plain]
Saving to: ‘/usr/local/bin/vncserver-stop’

vncserver-sto 100%      54  --.-KB/s    in 0s

2018-12-15 12:48:23 (643 KB/s) - ‘/usr/local/bin/vncserver-stop’ saved [54/54]


You can now start vncserver by running vncserver-start

It will ask you to enter a password when first time starting it.

The VNC Server will be started at 127.0.0.1:5901

You can connect to this address with a VNC Viewer you prefer

Connect to this address will open a window with Xfce4 Desktop Environmen





I hope you solve quickly

**Comment by asepnopan** [comment] 2021-02-13 10:55
I foud this thread, this may help you. https://www.facebook.com/groups/2628445374043698/permalink/2969901553231410/?app=fbl

**Comment by ErrorBot101** [comment] 2021-05-20 04:19
It's work on my machine i am using (Kali Linux desktop environment downloaded with andronix and tightvnc)

**First open a new window and bash your start-kali.sh file after getting root@localhost: **

_Run all command from below_

$ gpg --keyserver hkp://keys.gnupg.net --recv-key 7D8D0BF6

$ gpg -a --export 7D8D0BF6 | apt-key add -
$ apt-get update

$ apt-get install xfce4 
$ apt-get install xfce4-terminal
$ apt-get install tightvncserver

if you getting error **user veriable not set** try this

$ USER=root vncserver

and if you want to change your window size just type this

$ USER=root vncserver -geometry 1920x1080

(best for 5-6 inches phones and if you fit on your full screen maybe you got some laggy experience and dont forget to use costum dpi option under _application/display apperance/fonts/costume dpi_ and increase it to 120-150

maybe it's also work with ubuntu, arch Linux, Debian etc.

Thank you source: facebook post
